profiles/urls.py
from django.urls import path
from .views import UserListView, UserChartView

app_name = 'profiles'

urlpatterns = [
    path('', UserListView.as_view(), name='user-list'),
    path('<profile_id>/', UserChartView.as_view(), name='user-chart'),
]

skills/urls.py
from django.urls import path
from .views import skill_view, UserChartView, AllChartView


app_name = 'skills'


urlpatterns = [
    path('all/', AllChartView.as_view(), name='all-skills'),
    path('<profile_id>/', UserChartView.as_view(), name='user-skills'),
    path('', skill_view, name='my-skills'),
]

skills_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from skills.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('skills/', include('skills.urls', namespace='skills')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('', home_view, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

# Create your models here.


class Profile(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    avatar = models.ImageField(upload_to='uploads/img', validators=[FileExtensionValidator(allowed_extensions=['png'])], blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    @property
    def get_created(self):
        return self.created.strftime("%m/%d/%Y, %H:%M:%S")

    def __str__(self):
        return "{}-{}".format(self.name, self.get_created)

skills/models.py
from django.db import models
from profiles.models import Profile
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class Skill(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=220)
    score = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

    def __str__(self):
        return "{}-{}-{}".format(self.user, self.name, self.score)

profiles/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from .models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class UserChartView(LoginRequiredMixin, TemplateView):
    template_name = 'profiles/user_skills.html'

    def get_object(self):
        pk = self.kwargs.get('profile_id')
        return pk

    def get_context_data(self, **kwargs):
        context = super(UserChartView, self).get_context_data(**kwargs)
        profile = Profile.objects.get(name__id=self.get_object())
        qs = profile.skill_set.all()
        context["qs"] = qs
        return context


class UserListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'profiles/user_list.html'

skills/views.py
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.forms import inlineformset_factory
from django.views.generic import TemplateView
from .models import Skill
from profiles.models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.


def home_view(request):
    return render(request, 'skills/home.html', {})


class AllChartView(LoginRequiredMixin, TemplateView):
    template_name = 'skills/all_charts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Grouping by the 'name', creating a new variable 'total' and summing up the 'score'
        qs = Skill.objects.values('name').annotate(total=Sum('score'))
        # qs = Skill.objects.all()
        context["qs"] = qs
        return context


class UserChartView(LoginRequiredMixin, TemplateView):
    template_name = 'skills/user_skills.html'

    def get_object(self):
        pk = self.kwargs.get('profile_id')
        return pk

    def get_context_data(self, **kwargs):
        context = super(UserChartView, self).get_context_data(**kwargs)
        profile = Profile.objects.get(name__id=self.get_object())
        qs = profile.skill_set.all()
        context["qs"] = qs
        return context


@login_required
def skill_view(request):
    user_id = request.user.id
    profile = Profile.objects.get(pk=user_id)
    # Profile is parent_model and child_model is Skill, fields for the child_model
    SkillFormset = inlineformset_factory(Profile, Skill, fields='__all__', extra=1, can_delete=True)
    formset = SkillFormset(request.POST or None, instance=profile)
    if formset.is_valid():
        formset.save()

        return redirect('skills:my-skills')

    qs = profile.skill_set.all()

    context = {
        'formset': formset,
        'qs': qs,
    }

    return render(request, 'skills/add.html', context)

profiles/templates/_base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- semantic UI -->
        <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
        <!--Chart js-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
        <!-- jQuery -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

        <title>skill-site | {% block title %}{% endblock %}</title>
    </head>
    <body>
    {% include '_navbar.html' %}

    {% block scripts %}
    {% endblock %}

    <div class="container ui">
        {% block content %}
        {% endblock %}
    </div>
    </body>
</html>

profiles/templates/_navbar.html
{% url 'home' as path_home %}
{% url 'skills:my-skills' as path_my_skills %}
{% url 'skills:all-skills' as path_all_skills %}
{% url 'profiles:user-list' as path_users %}

<div class="ui inverted segment">
  <div class="ui inverted secondary pointing menu">
    <a href={{ path_home }} class="item {% if request.path == path_home %}active{% endif %}">
      Home
    </a>
    <a href={{ path_my_skills }} class="item {% if request.path == path_my_skills %}active{% endif %}">
      My skills
    </a>
    <a href={{ path_all_skills }} class="item {% if request.path == path_all_skills %}active{% endif %}">
      All skills
    </a>
    <a href={{ path_users }} class="item {% if request.path == path_users %}active{% endif %}">
      Users
    </a>
  </div>
</div>

profiles/templates/profiles/user_list.html
{% extends '_base.html' %}

{% block title %}user list{% endblock %}

{% block content %}
<table class="ui single line table">
    <thead>
        <tr>
            <th>Username</th>
            <th>Joined Date</th>
            <th>Skills</th>
        </tr>
    </thead>
    <tbody>
    {% for obj in object_list %}
    <tr>
        <td>{{ obj.name }}</td>
        <td>{{ obj.created|date }}</td>
        <td>
            <a href="{% url 'profiles:user-chart' obj.pk %}">
                <button class="ui primary button">
                    See
                </button>
            </a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

profiles/templates/profiles/user_skills.html
{% extends '_base.html' %}

{% block title %}user skills{% endblock %}

{% block scripts %}
{#    https://www.chartjs.org/docs/latest/#}
    <script>
        $(document).ready(function(){
            {# start code - making colors random #}
            getColor =() =>{
                r = getColorRange(0,255)
                g = getColorRange(0,255)
                b = getColorRange(0,255)
                op = 0.8
                color = 'rgb(' + r + ',' + g + ',' + b + ',' + op + ')'
                return color
            }

            getColorRange=(min, max)=>{
                return Math.floor(Math.random() * (max-min)) + min
            }
            {# end code - making colors random #}
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'pie',
                {#type: 'bar',#}
                data: {
                    labels: [{% for item in qs %}'{{ item.name }}',{% endfor %}],
                    {#labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],#}
                    datasets: [{
                        label: '# of Votes',
                        data: [{% for item in qs %}{{ item.score }},{% endfor %}],
                        {#data: [12, 19, 3, 5, 2, 3],#}
                        {# start code - making colors random #}
                        backgroundColor: [{% for item in qs %}getColor(),{% endfor %}],
                        {# end code - making colors random #}
                        {# start code - having one color for background #}
                        {#backgroundColor: 'rgba(255, 99, 132, 0.2)',#}
                        borderColor: 'rgba(255, 99, 132, 1)',
                        {# end code - having one color for background #}
                        {#backgroundColor: [#}
                        {#    'rgba(255, 99, 132, 0.2)',#}
                        {#    'rgba(54, 162, 235, 0.2)',#}
                        {#    'rgba(255, 206, 86, 0.2)',#}
                        {#    'rgba(75, 192, 192, 0.2)',#}
                        {#    'rgba(153, 102, 255, 0.2)',#}
                        {#    'rgba(255, 159, 64, 0.2)'#}
                        {#],#}
                        {#borderColor: [#}
                        {#    'rgba(255, 99, 132, 1)',#}
                        {#    'rgba(54, 162, 235, 1)',#}
                        {#    'rgba(255, 206, 86, 1)',#}
                        {#    'rgba(75, 192, 192, 1)',#}
                        {#    'rgba(153, 102, 255, 1)',#}
                        {#    'rgba(255, 159, 64, 1)'#}
                        {#],#}
                        borderWidth: 2
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        });
    </script>
{% endblock %}

{% block content %}
    <canvas id="myChart" width="400" height="300"></canvas>
{% endblock %}

skills/templates/skills/add.html
{% extends '_base.html' %}

{% block title %}my skills{% endblock %}

{% block scripts %}
{#    https://www.chartjs.org/docs/latest/#}
    <script>
        $(document).ready(function(){
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for item in qs %}'{{ item.name }}',{% endfor %}],
                    {#labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],#}
                    datasets: [{
                        label: '# of points',
                        data: [{% for item in qs %}{{ item.score }},{% endfor %}],
                        {#data: [12, 19, 3, 5, 2, 3],#}
                        backgroundColor: 'rgba(255, 99, 132, 0.5)',
                        borderColor: 'rgba(255, 99, 132, 1)',
                        {#backgroundColor: [#}
                        {#    'rgba(255, 99, 132, 0.2)',#}
                        {#    'rgba(54, 162, 235, 0.2)',#}
                        {#    'rgba(255, 206, 86, 0.2)',#}
                        {#    'rgba(75, 192, 192, 0.2)',#}
                        {#    'rgba(153, 102, 255, 0.2)',#}
                        {#    'rgba(255, 159, 64, 0.2)'#}
                        {#],#}
                        {#borderColor: [#}
                        {#    'rgba(255, 99, 132, 1)',#}
                        {#    'rgba(54, 162, 235, 1)',#}
                        {#    'rgba(255, 206, 86, 1)',#}
                        {#    'rgba(75, 192, 192, 1)',#}
                        {#    'rgba(153, 102, 255, 1)',#}
                        {#    'rgba(255, 159, 64, 1)'#}
                        {#],#}
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        });
    </script>
{% endblock %}

{% block content %}

    <div class="ui grid">
        <div class="four wide column">
            <form action="" method="POST" class="form ui" autocomplete="off">
                {% csrf_token %}
                {{ formset.as_p }}
                <button class="secondary button ui" type="submit">Send</button>
            </form>
        </div>
        <div class="twelve wide column">
            <canvas id="myChart" width="400" height="300"></canvas>
        </div>
    </div>


{% endblock %}

skills/templates/skills/all_charts.html
{% extends '_base.html' %}

{% block title %}my skills{% endblock %}

{% block scripts %}
{#    https://www.chartjs.org/docs/latest/#}
    <script>
        $(document).ready(function(){
            var ctx = document.getElementById('myChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: [{% for item in qs %}'{{ item.name }}',{% endfor %}],
                    {#labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],#}
                    datasets: [{
                        label: '# of points',
                        data: [{% for item in qs %}{{ item.total }},{% endfor %}],
                        {#data: [{% for item in qs %}{{ item.score }},{% endfor %}],#}
                        {#data: [12, 19, 3, 5, 2, 3],#}
                        backgroundColor: 'rgba(44, 130, 201, 0.5)',
                        borderColor: 'rgba(0, 0, 0, 1)',
                        {#backgroundColor: [#}
                        {#    'rgba(255, 99, 132, 0.2)',#}
                        {#    'rgba(54, 162, 235, 0.2)',#}
                        {#    'rgba(255, 206, 86, 0.2)',#}
                        {#    'rgba(75, 192, 192, 0.2)',#}
                        {#    'rgba(153, 102, 255, 0.2)',#}
                        {#    'rgba(255, 159, 64, 0.2)'#}
                        {#],#}
                        {#borderColor: [#}
                        {#    'rgba(255, 99, 132, 1)',#}
                        {#    'rgba(54, 162, 235, 1)',#}
                        {#    'rgba(255, 206, 86, 1)',#}
                        {#    'rgba(75, 192, 192, 1)',#}
                        {#    'rgba(153, 102, 255, 1)',#}
                        {#    'rgba(255, 159, 64, 1)'#}
                        {#],#}
                        borderWidth: 3
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        });
    </script>
{% endblock %}

{% block content %}
    <canvas id="myChart" width="400" height="300"></canvas>
{% endblock %}

skills/templates/skills/home.html
{% extends '_base.html' %}

{% block title %}
    home
{% endblock %}

{% block content %}
    <div class="ui icon message">
    <i class="inbox icon"></i>
        <div class="content">
            <div class="header">
              Do you have any questions?
            </div>
            If so contact me on my email: info@example.com</p>
        </div>
    </div>

    <div class="ui segment">
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>
    <br>
    <div class="sixteen wide column" style="text-align: center">
        <a href="{% url 'skills:my-skills' %}">
            <button class="massive primary ui button">
                <i class="chart line icon"></i> My skills
            </button>
        </a>
    </div>
    </div>
{% endblock %}